modLoader="javafml"
loaderVersion="[1,)"
license="ARR"

[[mods]]
modId="advancerepair"
version="1.3"
displayName="Advance Repair"
logoFile="logo.png"
authors="Gamerofpro"
description='''
Advance Repair is a gameplay-focused mod that improves how repairing works in anvils.

- Multiple materials can repair gear
- Custom repair efficiency system
- XP cost scaling based on enchantments and trims
- Supports Netherite, Diamond, Iron, Leather, and Chainmail

Designed to make survival gameplay more flexible and less grindy while staying balanced.
'''

[[dependencies.advancerepair]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.advancerepair]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
